// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBquKeYVuTQr0RRRnqf7mxNGs8LMfH-S5Y',
    appId: '1:173608730656:web:a6c6b835e1b50a4aa93c45',
    messagingSenderId: '173608730656',
    projectId: 'habit-5643f',
    authDomain: 'habit-5643f.firebaseapp.com',
    storageBucket: 'habit-5643f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwhZ_BOsEV0a5ySqqtCEH5GwchxPTLnjw',
    appId: '1:173608730656:android:ba391ca072fe3e64a93c45',
    messagingSenderId: '173608730656',
    projectId: 'habit-5643f',
    storageBucket: 'habit-5643f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB1JA2mP8XEpK8KPgxqndTnSbRmMv3nRY',
    appId: '1:173608730656:ios:2cc794b6ee159dbba93c45',
    messagingSenderId: '173608730656',
    projectId: 'habit-5643f',
    storageBucket: 'habit-5643f.appspot.com',
    iosBundleId: 'com.example.habit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB1JA2mP8XEpK8KPgxqndTnSbRmMv3nRY',
    appId: '1:173608730656:ios:2cc794b6ee159dbba93c45',
    messagingSenderId: '173608730656',
    projectId: 'habit-5643f',
    storageBucket: 'habit-5643f.appspot.com',
    iosBundleId: 'com.example.habit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBquKeYVuTQr0RRRnqf7mxNGs8LMfH-S5Y',
    appId: '1:173608730656:web:df7f92a19222ed53a93c45',
    messagingSenderId: '173608730656',
    projectId: 'habit-5643f',
    authDomain: 'habit-5643f.firebaseapp.com',
    storageBucket: 'habit-5643f.appspot.com',
  );
}
